language: ruby
os: osx
before_install:
  - ruby --version
  - gem --version
  - python --version
  - brew update
  - brew --version
script:
  - bundle exec thor test:all
env:
  - DMGBUILD_VERSION=stable
  - DMGBUILD_VERSION=head
